version: '3.9'
name: nestjs-graphql-schema-first

services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgrespassword
